### ISSUE TITLE
Images to spike

### ISSUE THREAD

**Issue by meltingCat** [chanokin/pyDVS#3]
Hi~
I ran "python mnist_to_spikes.py" and create txt files. What does the message mean down below?
Thanks!

```
595 0.000000
659 0.000000
533 0.000000
597 0.000000
661 0.000000
725 0.000000
789 0.000000
853 0.000000
917 0.000000
981 0.000000
1045 0.000000
1109 0.000000
1173 0.000000
1237 0.000000
1301 0.000000
1365 0.000000
1429 0.000000
791 0.000000
855 0.000000
919 0.000000
983 0.000000
1047 0.000000
1111 0.000000
1175 0.000000
1239 0.000000
1303 0.000000
1367 0.000000
1431 0.000000
1369 0.000000
1433 0.000000
1371 0.000000
1435 0.000000
1309 0.000000
1373 0.000000
1247 0.000000
1311 0.000000
1375 0.000000
1249 0.000000
1313 0.000000
1187 0.000000
1251 0.000000
1315 0.000000
1189 0.000000
1253 0.000000
1127 0.000000
1191 0.000000
1255 0.000000
1129 0.000000
1193 0.000000
1067 0.000000
1131 0.000000
1195 0.000000
1005 0.000000
1069 0.000000
1133 0.000000
1007 0.000000
1071 0.000000
945 0.000000
1009 0.000000
947 0.000000
1011 0.000000
885 0.000000
949 0.000000
1013 0.000000
887 0.000000
951 0.000000
1015 0.000000
889 0.000000
```

**Comment by chanokin** [comment]
Hi, sorry for the reaaaaaally late reply. Do you mean that's the output in the text file? It's been a while since I used this so I'm a bit rusty.

**Comment by meltingCat** [comment]
@chanokin Yes, I mean the output in the text file.

**Comment by chanokin** [comment]
Ah ok, so the first number should be the x|y|polarity and the second the time. Are you encoding a single image? 
To extract the info of the first number, you could parse it as an unsigned 32-bit integer and then do some shifts and masks. I believe the default is using the log2(image width), in this case width is set to 32 and the shift would 5 bits per coordinate, something like
```python
x = num >> 6
y = (num >> 1) & uint8(width -1)
polarity = (num & 1)
```

**Comment by meltingCat** [comment]
@chanokin Yes, I am encoding a single image.Thanks.
